"""Generate openEMS Python driver scripts (cartesian patch, after official tutorial)."""

from __future__ import annotations

from pathlib import Path

from pilot.schema import SimulationTaskSpec
from pilot.logging_utils import get_logger

_LOG = get_logger("em_solver.openems_builder")

# Template based on openEMS `python/Tutorials/Simple_Patch_Antenna.py` (BSD/GPL per upstream).
OPENEMS_PATCH_SCRIPT_TEMPLATE = r'''# -*- coding: utf-8 -*-
"""
Auto-generated by Pilot — rectangular microstrip patch, openEMS FDTD.
Derived from openEMS Simple_Patch_Antenna tutorial structure.
Run: python run_openems_patch.py
"""
import os
import sys
import numpy as np

# Headless plotting
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from CSXCAD import ContinuousStructure
from openEMS import openEMS
from openEMS.physical_constants import EPS0, C0

SIM_PATH = r"__SIM_PATH__"
os.makedirs(SIM_PATH, exist_ok=True)

# --- Parameters (injected by Pilot) ---
unit = 1e-3  # mm
patch_width  = __PATCH_WIDTH__   # x, mm
patch_length = __PATCH_LENGTH__  # y, mm
substrate_epsR   = __EPS_R__
substrate_kappa  = __KAPPA__
substrate_width  = __SUB_W__
substrate_length = __SUB_L__
substrate_thickness = __SUB_H__
substrate_cells = __SUB_CELLS__
feed_pos = __FEED_POS__
feed_R = __FEED_R__
SimBox = np.array([__SBX__, __SBY__, __SBZ__])
f0 = __F0_HZ__
fc = __FC_HZ__
NrTS = __NR_TS__
EndCriteria = __END_CRIT__

### FDTD setup
FDTD = openEMS(NrTS=NrTS, EndCriteria=EndCriteria)
FDTD.SetGaussExcite(f0, fc)
FDTD.SetBoundaryCond(["MUR", "MUR", "MUR", "MUR", "MUR", "MUR"])

CSX = ContinuousStructure()
FDTD.SetCSX(CSX)
mesh = CSX.GetGrid()
mesh.SetDeltaUnit(unit)
mesh_res = C0 / (f0 + fc) / unit / 20

mesh.AddLine("x", [-SimBox[0] / 2, SimBox[0] / 2])
mesh.AddLine("y", [-SimBox[1] / 2, SimBox[1] / 2])
mesh.AddLine("z", [-SimBox[2] / 3, SimBox[2] * 2 / 3])

patch = CSX.AddMetal("patch")
start = [-patch_width / 2, -patch_length / 2, substrate_thickness]
stop = [patch_width / 2, patch_length / 2, substrate_thickness]
patch.AddBox(priority=10, start=start, stop=stop)
FDTD.AddEdges2Grid(dirs="xy", properties=patch, metal_edge_res=mesh_res / 2)

substrate = CSX.AddMaterial("substrate", epsilon=substrate_epsR, kappa=substrate_kappa)
start = [-substrate_width / 2, -substrate_length / 2, 0]
stop = [substrate_width / 2, substrate_length / 2, substrate_thickness]
substrate.AddBox(priority=0, start=start, stop=stop)
mesh.AddLine("z", np.linspace(0, substrate_thickness, substrate_cells + 1))

gnd = CSX.AddMetal("gnd")
start = [-substrate_width / 2, -substrate_length / 2, 0]
stop = [substrate_width / 2, substrate_length / 2, 0]
gnd.AddBox(start, stop, priority=10)
FDTD.AddEdges2Grid(dirs="xy", properties=gnd)

start = [feed_pos, 0, 0]
stop = [feed_pos, 0, substrate_thickness]
port = FDTD.AddLumpedPort(1, feed_R, start, stop, "z", 1.0, priority=5, edges2grid="xy")

mesh.SmoothMeshLines("all", mesh_res, 1.4)

def main() -> int:
    print("Pilot openEMS: running FDTD in", SIM_PATH, file=sys.stderr)
    FDTD.Run(SIM_PATH, cleanup=True)
    n = __N_FREQ__
    f = np.linspace(max(1e9, f0 - fc), f0 + fc, n)
    port.CalcPort(SIM_PATH, f)
    s11 = port.uf_ref / port.uf_inc
    s11_db = 20.0 * np.log10(np.maximum(np.abs(s11), 1e-15))
    out_csv = os.path.join(os.path.dirname(__file__), "s11.csv")
    data = np.column_stack([f / 1e9, s11_db])
    hdr = "freq_ghz,s11_db"
    np.savetxt(out_csv, data, delimiter=",", header=hdr, comments="")
    print("Wrote", out_csv, file=sys.stderr)
    fig, ax = plt.subplots(figsize=(7, 4), tight_layout=True)
    ax.plot(f / 1e9, s11_db, "k-", lw=2)
    ax.grid(True)
    ax.set_xlabel("Frequency (GHz)")
    ax.set_ylabel("S11 (dB)")
    ax.set_title("Return loss (openEMS)")
    png = os.path.join(os.path.dirname(__file__), "s11.png")
    fig.savefig(png, dpi=120)
    print("Wrote", png, file=sys.stderr)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
'''


def build_openems_patch_script(spec: SimulationTaskSpec, run_dir: Path) -> Path:
    """Write `run_openems_patch.py` under run_dir; returns path to script."""
    import numpy as np

    eps0 = 8.8541878128e-12  # vacuum permittivity (F/m); keep builder import-free of openEMS

    run_dir = run_dir.resolve()
    run_dir.mkdir(parents=True, exist_ok=True)
    sim_path = run_dir / "openems_workspace"
    sim_path.mkdir(parents=True, exist_ok=True)

    pw = float(spec.geometry.patch_width_mm or 32.0)
    pl = float(spec.geometry.patch_length_mm or 40.0)
    h = float(spec.geometry.substrate_thickness_mm)
    er = float(spec.material.relative_permittivity)
    tan_d = float(spec.material.loss_tangent)
    f0 = float(spec.frequency.center_ghz) * 1e9
    fc = min(0.5e9, f0 * 0.25)

    kappa = float(tan_d * 2 * np.pi * f0 * eps0 * er)

    sub_w = max(60.0, max(pw, pl) * 2.2)
    sub_l = max(60.0, max(pw, pl) * 2.2)
    feed_pos = float(np.clip(-0.2 * pw, -pw * 0.45, -1.0))

    sbx = max(200.0, sub_w * 2.5)
    sby = max(200.0, sub_l * 2.5)
    sbz = max(150.0, h * 40)

    cells = max(4, min(8, int(round(h / 0.35))))

    code = OPENEMS_PATCH_SCRIPT_TEMPLATE
    code = code.replace("__SIM_PATH__", str(sim_path))
    code = code.replace("__PATCH_WIDTH__", str(round(pw, 4)))
    code = code.replace("__PATCH_LENGTH__", str(round(pl, 4)))
    code = code.replace("__EPS_R__", str(er))
    code = code.replace("__KAPPA__", repr(kappa))
    code = code.replace("__SUB_W__", str(round(sub_w, 4)))
    code = code.replace("__SUB_L__", str(round(sub_l, 4)))
    code = code.replace("__SUB_H__", str(round(h, 4)))
    code = code.replace("__SUB_CELLS__", str(cells))
    code = code.replace("__FEED_POS__", str(round(feed_pos, 4)))
    code = code.replace("__FEED_R__", "50.0")
    code = code.replace("__SBX__", str(round(sbx, 2)))
    code = code.replace("__SBY__", str(round(sby, 2)))
    code = code.replace("__SBZ__", str(round(sbz, 2)))
    code = code.replace("__F0_HZ__", str(f0))
    code = code.replace("__FC_HZ__", str(fc))
    code = code.replace("__NR_TS__", "18000")
    code = code.replace("__END_CRIT__", "1e-3")
    code = code.replace("__N_FREQ__", "401")

    script_path = run_dir / "run_openems_patch.py"
    script_path.write_text(code, encoding="utf-8")
    _LOG.info("Wrote openEMS driver script %s", script_path)
    return script_path
